import { LEVELS } from '../enums/settings';
import { createDictionaryLoader, type DeckCache, type DeckSource } from './createLoader';
import advanced from './ru/advanced.json';
import easy from './ru/easy.json';
import medium from './ru/medium.json';
import pro from './ru/pro.json';

const LANGUAGE = 'ru';
const REVISION = 1;

/**
 * Decks are generated by scripts/build-dictionaries.mjs and ship inside the
 * app bundle, so every level is available offline from the very first launch.
 */
const decks: Record<LEVELS, string[]> = {
  [LEVELS.easy]: easy,
  [LEVELS.medium]: medium,
  [LEVELS.advanced]: advanced,
  [LEVELS.pro]: pro,
};

const source: DeckSource = async (level) => decks[level];

/**
 * Deliberately empty: the bundle already holds every deck, so there is nothing
 * worth persisting. Swap in AsyncStorage here if decks are ever downloaded.
 */
const cache: DeckCache = {
  read: async () => undefined,
  write: async () => {},
};

const loader = createDictionaryLoader({
  source,
  cache,
  language: LANGUAGE,
  revision: REVISION,
});

export function loadWords(level: LEVELS): Promise<string[]> {
  return loader.loadWords(level);
}

export { shuffle } from './createLoader';
